version: '3.8'

services:
  catalogo:
    image: nginx:alpine
    container_name: catalogo
    ports:
      - "8080:80"
    volumes:
      - ./catalogo-vehicular/dist/catalogo-vehicular/browser:/usr/share/nginx/html
      - ./nginx/catalogo.conf:/etc/nginx/conf.d/default.conf
    restart: always

  cotizador:
    image: nginx:alpine
    container_name: cotizador
    ports:
      - "8081:80"
    volumes:
      - ./cotizador-vehicular/dist/cotizador-vehicular/browser:/usr/share/nginx/html
      - ./nginx/cotizador.conf:/etc/nginx/conf.d/default.conf
    restart: always